### ISSUE TITLE
☂️ Shut down production service

### ISSUE THREAD

**Issue by Mr0grog** [usdigitalresponse/univaf#1550]
On June 15, 2023, well be shutting down the production service, but will be keeping the source code available here, as well as the archived data at [archives.getmyvax.org](https://archives.getmyvax.org) and a placeholder page at [getmyvax.org](https://getmyvax.org).

What needs to be done to wrap things up?

- [x] After Monday’s dependency updates, disable Dependabot (maybe leave security updates on?). (#1564)
- [x] Add maintenance status notice to README (#1588)
- [x] Create a home page for https://archives.getmyvax.org with some minimal documentation (how to construct download paths and information about file formats). I’ve been meaning to do this for a while, but it’s more critical now that the exiting docs page will be gone. (#1570)
- [x] Create a tombstone and 404 page for https://getmyvax.org. (#1569)
    - Publish to GitHub pages (instead of the existing demo UI, so this will require changing the [`ui-deploy.yml` actions workflow](https://github.com/usdigitalresponse/univaf/blob/fdcfe041238c39d6ad33898ab4642c1edd037bcd/.github/workflows/ui-deploy.yml).
    - This can probably just replace the [demo UI in the `ui` folder](https://github.com/usdigitalresponse/univaf/tree/main/ui); I don’t think there’s a real reason to keep that code around and it hasn’t been well maintained anyway.
- [x] Do a final pass on docs; make sure it’s *reasonably* clear how to fork and deploy yourself.
- [x] Clean up dangling PRs and issues.
    - We should probably close all lingering PRs.
    - I plan to leave issues that someone forking and re-deploying might want to do (e.g. #202) but close others that just aren’t relevant anymore (I’ve already done a bunch of these).
- [x] Make a copy of the existing Terraform files in `/terraform/deprecated` (similar to what we did during the failed switch to Render; see #930) and add a README there that describes the fact that those files represent a production deployment, while the top-level `/terraform` directory is the archived/shut-down deployment. (#1565)
- [x] Update loader schedules so they don’t run at or after `2023-06-16T00:00:00Z`. (e.g. a schedule like `cron(1/15 * * * ? *)` should become `cron(1/15 * 1-15 6 ? *)`). (#1566)
- [x] Wait until the start of June 16 UTC.
- [x] Switch DNS for `getmyvax.org` to point to tombstone page on GitHub pages. (#1571)
- [x] Make a final dump of the database (excepting the contents of the `availability_log` table) in PGSQL and post to the archives. See https://github.com/usdigitalresponse/univaf/blob/main/docs/runbook/postgres.md#copying-the-database
- [x] Update archives home page with final dump dates.
- [x] Remove all scheduled jobs (#1575)
- [x] Remove API CloudFront instance (#1576)
- [x] Remove API Load Balancers and services (#1577)
- [x] Destroy the database (#1582)
- [x] Clean up any remaining AWS resources not needed for the archives S3 bucket and DNS. (#1585)
- [x] Remove monitors and SLAs in Datadog

**Comment by Mr0grog** [comment]
Dumped a final copy of the DB to PG SQL and SQLite and uploaded to S3. Still need to add info to the archives PR: #1570

**Comment by Mr0grog** [comment]
All the running services in AWS have been torn down, but there are some other lightweight things to get rid of:
- ECS Cluster (nothing is running it now)
- Actual database in RDS
- Bastion
- Subnets
- Docker images in ECR

Then I need to clean up the Terraform files.

Finally, there is some more general docs and repo cleanup to do, including finishing out docs for the archives (#1570).

I might do a bit more today, but will probably leave most of that for next week.
