### ISSUE TITLE
☂ Freeze a v1 of the API

### ISSUE THREAD

**Issue by Mr0grog** [usdigitalresponse/univaf#214]
**This is a meta-issue.**

We currently have routes at `/api/edge/*`, but the implicit contract with `edge` is that things aren’t super stable (we try not to break partners, but could easily accidentally break users we don’t know about). It would be good to get something we can call a `v1` of the API and treat that like a semantic version (we can add to it, but not fundamentally change the format of an existing field or remove something).

- [x] Remove support for `?external_id_format` when VtS is ready (#213)
- [x] Drop `provider_locations.eligibility` field (#154)
- [x] Formalize response format for errors (#66)
- [x] ~Consider changing the data model to match more closely with Vaccinate the States (#49)~ *(The bits worth considering adding are mostly additions, not renamings, removals, or consolidations, so are better done post v1.)*
- [ ] Make `/api/v1/*` routes
- [ ] Update documentation

**Comment by Mr0grog** [comment]
This is no longer relevant with the service sunsetting in a month.
