### ISSUE TITLE
Open Source!

### ISSUE THREAD

**Issue by Mr0grog** [usdigitalresponse/univaf#233]
We got the go-ahead from New Jersey to open-source this project! Specific support for partner issues remains higher priority, but should be next in line after those immediate needs, since open-sourcing helps federal partners and contractors make use of the tools here with fewer restrictions.

What needs to happen in order to make that a reality?

- [x] Make sure we use consistent naming everywhere (“UNIVAF” / `univaf` for discussions of code and components, “Vaccine Appointments API” for externally-focused things). (#191)
- [x] Clean up docs and README to clearly describe project goals and structure. (#259)
- [x] List contributors in README. (#259)
- [x] Carefully review codebase for any sensitive information or credentials.
- [x] Add `LICENSE` file and license info to README (should be Apache 2.0, per USDR policy: https://policies.usdigitalresponse.org/data-and-software-guidelines#licensing). (#259)
- [x] Consider renaming the repo `univaf` or `vaccine-appointment-api`.
- [x] Make the repo public!

**Comment by Mr0grog** [comment]
DONE! 🎉
