### ISSUE TITLE
Pull slot/capacity data out of `availability.meta`

### ISSUE THREAD

**Issue by Mr0grog** [usdigitalresponse/univaf#89]
In order to enable better historical data analysis, we want to pull some fields out of `availability.meta` and put them directly on `availability`.

The current schema for availability is:

```sql
id SERIAL PRIMARY KEY,
provider_location_id varchar(64) NOT NULL,
source varchar NOT NULL,
valid_at timestamp with time zone NOT NULL,
checked_at timestamp with time zone NOT NULL,
available varchar NOT NULL,
meta jsonb,
is_public boolean DEFAULT true
```

And we’ll change it to:

```sql
id SERIAL PRIMARY KEY,
provider_location_id varchar(64) NOT NULL,
source varchar NOT NULL,
valid_at timestamp with time zone NOT NULL,
requested_at timestamp with time zone NOT NULL,
available varchar NOT NULL,
available_count int,
products varchar[],
doses varchar[],
capacity jsonb,
slots jsonb,
meta jsonb,
is_public boolean DEFAULT true,
```

- Add `available_count`: a count of available appointments. NULL if not known.
- Add `products`: an array of vaccine products being offered. NULL if not known.
- Add `doses`: an array of vaccine doses being offered. NULL if not known.
- Add `capacity`: a JSON array of objects representing dates with/without capacity. NULL if not known. Schema should be be:

    ```js
    {
      date: "<ISO_8601_datestamp>",
      available: "yes" | "no", // Only here in case `available_count` is not provided by the source
      available_count: <int> | null,
      unavailable_count: <int> | null,
      products: <string[]> | null,
      dose: <string> | null
    }
    ```

- Add `slots`: a JSON array of objects representing specific times with/without capacity. NULL if not known. Schema should be be:

    ```js
    {
      start: "<timestamp>",
      end: "<timestamp>" | null,
      available: "yes" | "no",
      available_count: <int> | null,
      unavailable_count: <int> | null,
      products: <string[]> | null,
      dose: <string> | null
    }
    ```

    Even though these are *intended* to represent specific appointment slots, they still may have capacity information — we’re somewhat hampered by the SMART Scheduling Links spec in that slots there can have any timeframe or granularity. :\

After changing the schema, the `/update` endpoint will need to accept current data (which sometimes has this information in `meta`) and pull the relevant fields out of `meta` and directly onto `availability`. We should also handle the Walgreens format (which is slightly different than what’s spec’d here) and change it to this. Finally, we should validate that the data meets this format. (We *could* do that in SQL by having capacity rows and slots be other tables, but I think that’s going get messy in terms of complexity; better to treat this as a single chunk of data about current availability for now.)

- [x] Update Walgreens formats in loader to match this (#95)
- [x] DB migration
- [x] Fix `updateLocation()` in `db.ts`
- [x] Fix queries that read data in `db.ts`
- [x] Add validation for JSON formats (`capacity` and `slots`)
- [x] Validate that we set NULL instead of empty arrays (or vice-versa, just be consistent)
- [x] Ensure that in `slots` and `capacity`, keys with `null` values are left out rather than actually being set to null.
- [x] Auto-populate `capacity` based on `slots` if only `slots` is present in the update
- [x] Auto-populate top-level `products` and `doses` from `capacity` or `slots`
- [x] Handle old format with the data inside `meta` in `/update`

*Update: added available_count*
